Updated makefile to run tests

diff --git a/test/makefile b/test/makefile
--- a/test/makefile
+++ b/test/makefile
@@ -1,7 +1,7 @@
 # Makefile automatically generated by ghdl
 # Version: GHDL 0.36 (v0.36) [Dunoon edition] - GCC back-end code generator
 # Command used to generate this makefile:
-# ghdl --gen-makefile txmbxtb
+# ghdl --gen-makefile lan9254esctb
 
 
 CROSS=
@@ -14,8 +14,9 @@ SIITOOL=siitool
 -include config.local.mk
 
 vpath %.vhd ../hdl
+vpath %.c   ../hdl
 
-PROG+=lan9254escrun txmbxtb eoetb
+PROG+=lan9254escrun lan9254esctb txmbxtb eoetb
 PROG+=strmframebuftb udp2bustb devicedna7tb
 PROG+=udp2busmuxtb
 PROG+=escfoetb strmfifosynctb
@@ -39,7 +40,7 @@ OBJS+=StrmFifoSync.o
 OBJS+=ESCFoEPkg.o
 OBJS+=Bus2BusAsync.o
 
-TOPS+=Lan9254ESCrun.o TxMBXTb.o EoETb.o StrmFrameBufTb.o
+TOPS+=Lan9254ESCTb.o  Lan9254ESCrun.o TxMBXTb.o EoETb.o StrmFrameBufTb.o
 TOPS+=Udp2BusTb.o DeviceDna7Tb.o Udp2BusMuxTb.o ESCFoETb.o StrmFifoSyncTb.o
 TOPS+=Bus2BusAsyncTb.o
 TOPS+=Bus2BusAsyncAltTb.o
@@ -55,6 +56,8 @@ lan9254escrun: $(OBJS) Lan9254ESCrun.o
 	$(GHDL) -e -fsynopsys -Wl,readWriteSim.o $(GHDLFLAGS) $@
 
 # Elaboration target
+lan9254esctb: $(OBJS) Lan9254ESCTb.o
+	$(GHDL) -e $(GHDLFLAGS) $@
 
 bus2busasynctb: $(OBJS) Bus2BusAsyncTb.o
 	$(GHDL) -e $(GHDLFLAGS) $@
@@ -90,8 +93,15 @@ strmfifosynctb: StrmFifoSyncTb.o $(OBJS)
 	$(GHDL) -e $(GHDLFLAGS) -fsynopsys $@
 
 # Run target
-run: $(filter %tb,$(PROG))
-	for tst in $^; do $(GHDL) -r $$tst $(GHDLRUNFLAGS); done
+test: $(filter-out %run,$(PROG))
+	(for i in $^; do \
+		echo "Running test $$i"; \
+		if ! $(GHDL) -r $$i $(GHDLRUNFLAGS); then \
+			echo "TEST FAILED";\
+			exit; \
+		fi;\
+	done)
+	echo "All Tests PASSED"
 
 # old method - now use the tool
 #EEPROMContentPkg.vhd: eeprom.bin gen-prom.awk
@@ -123,6 +133,8 @@ eeprom.bin: test.xml
 ##MM	$(GHDL) -a $(GHDLFLAGS) $<
 ##MMLan9254HbiSoft.o: Lan9254HbiSoft.vhd
 ##MM	$(GHDL) -a $(GHDLFLAGS) $<
+##MMLan9254ESCTb.o: Lan9254ESCTb.vhd
+##MM	$(GHDL) -a $(GHDLFLAGS) $<
 ##MMLan9254ESCrun.o: Lan9254ESCrun.vhd
 ##MM	$(GHDL) -a $(GHDLFLAGS) $<
 %.o: %.vhd
@@ -133,6 +145,7 @@ Lan9254ESC.o:  Lan9254Pkg.o Lan9254ESCPkg.o EEEmulPkg.o RxPDOSoft.o IlaWrappersP
 EEEmulPkg.o: EEPROMContentPkg.o Lan9254Pkg.o Lan9254ESCPkg.o
 Lan9254Hbi.o:  Lan9254Pkg.o Lan9254ESCPkg.o
 Lan9254HbiSoft.o:  Lan9254Pkg.o Lan9254Hbi.o Lan9254ESCPkg.o
+Lan9254ESCTb.o:  $(OBJS)
 Lan9254ESCrun.o: $(OBJS)
 TxMBXTb.o:       $(OBJS)
 EoETb.o:         $(OBJS)
@@ -166,4 +179,4 @@ StrmFifoSyncTb.o: $(OBJS)
 clean:
 	$(RM) $(OBJS) $(PROG) dump.ghw work-*.cf $(addprefix e~, $(addsuffix .o,$(PROG))) $(TOPS) EEPROMContentPkg.vhd eeprom.bin $(EVRPDO_S:%.vhd=%.o)
 
-.PHONY: clean all run
+.PHONY: clean all test
